num1 = float(input("Введите первое число: "))
num2 = float(input("Введите второе число: "))
print(f"Сумма: {num1 + num2}")
print(f"Разность: {num1 - num2}")
print(f"Произведение: {num1 * num2}")
print(f"Деление: {num1 / num2}")
print(f"Остаток от деления: {num1 % num2}")